// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_cqFe04q6rfg8H5bBWv4XpEpwW4uN7o',
    appId: '1:391458076633:web:b10d4cba1ad21c05fbcbc8',
    messagingSenderId: '391458076633',
    projectId: 'car-ping-9d4f8',
    authDomain: 'car-ping-9d4f8.firebaseapp.com',
    storageBucket: 'car-ping-9d4f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1euBHJwicf_4qHj8dtmLSaCZo07MvnHU',
    appId: '1:391458076633:android:5560b0a8f3ca7ca3fbcbc8',
    messagingSenderId: '391458076633',
    projectId: 'car-ping-9d4f8',
    storageBucket: 'car-ping-9d4f8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIjaOZdYiVoZr9t8b5L6eBLnjIqFZS3M',
    appId: '1:391458076633:ios:7cb0299e5abff29dfbcbc8',
    messagingSenderId: '391458076633',
    projectId: 'car-ping-9d4f8',
    storageBucket: 'car-ping-9d4f8.firebasestorage.app',
    iosBundleId: 'com.parktagapp.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlIjaOZdYiVoZr9t8b5L6eBLnjIqFZS3M',
    appId: '1:391458076633:ios:7cb0299e5abff29dfbcbc8',
    messagingSenderId: '391458076633',
    projectId: 'car-ping-9d4f8',
    storageBucket: 'car-ping-9d4f8.firebasestorage.app',
    iosBundleId: 'com.parktagapp.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_cqFe04q6rfg8H5bBWv4XpEpwW4uN7o',
    appId: '1:391458076633:web:ce99e9bcd1bc7afefbcbc8',
    messagingSenderId: '391458076633',
    projectId: 'car-ping-9d4f8',
    authDomain: 'car-ping-9d4f8.firebaseapp.com',
    storageBucket: 'car-ping-9d4f8.firebasestorage.app',
  );
}
